name: OpenTofu Deploy

on:
  push:
    branches:
      - main
      - staging

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Init OpenTofu
        run: |
          cd infra
          opentofu init

      - name: Run Plan for ${{ matrix.environment }}
        run: |
          cd infra
          opentofu plan -var-file="environments/${{ matrix.environment }}.tfvars"

  apply:
    runs-on: ubuntu-latest
    needs: plan
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup OpenTofu
        run: |
          curl -sSL https://opentofu.org/install.sh | bash

      - name: Set up Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run OpenTofu Apply for ${{ matrix.environment }}
        run: |
          cd infra
          opentofu apply -var-file="${{ matrix.environment }}.tfvars" -auto-approve
