name: Deploy Azure Infra
on:
  push:
    branches:
      - main
      - staging

permissions:
  id-token: write
  contents: read

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_USE_OIDC: "true"

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Format files
        working-directory: infra
        continue-on-error: true
        run: tofu fmt -check

      - name: Init OpenTofu
        working-directory: infra
        run: tofu init

      - name: Switch workspace
        working-directory: infra
        run: tofu workspace select -or-create ${{ github.ref_name }}

      - name: Plan changes
        working-directory: infra
        run: tofu plan -var-file="environments/${{ github.ref_name }}.tfvars" -out=terraform.tfstate -input=false

      - name: Upload tfstate as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tf-state
          path: infra/terraform.tfstate

  apply:
    runs-on: ubuntu-latest
    needs: plan
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Set up Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Download tfstate artifact
        uses: actions/download-artifact@v4
        with:
          name: tf-state
          path: $GITHUB_WORKSPACE/infra

      - name: Init OpenTofu
        working-directory: infra
        run: tofu init

      - name: Switch workspace
        working-directory: infra
        run: tofu workspace select -or-create ${{ github.ref_name }}

      - name: Apply changes
        working-directory: infra
        run: tofu apply -var-file="environments/${{ github.ref_name }}.tfvars" -auto-approve
